### PR TITLE
Added git bash task (corrected)

### PR DESCRIPTION
**Pull request by ragekit**
Added git bash task that benefits from cmder enhancements and UI.

Sorry for pushing in master, i forgot to switch branch

### CODE REVIEW

**Comment by MartiUK** [comment]
Could you sort out your pull request, you're pulling in other commits.

**Comment by ragekit** [comment]
hum, never did a pull request before, so i don't know. Whatever, it wasn't a usefull change.

**Comment by MartiUK** [comment]
Alright no problem. Thanks anyway.

**Comment by Jackbennett** [comment]
@ragekit Just so you know, I think I did the same thing as you. I think you made your patch-1 branch from your fork of master then submitted the pull request to development. 

The extra commits are the difference between master and development to get up to your patch-1.

I think roughly the flow to do is;
- Fetch bliker upstream;
- checkout upstream/development;
- commit/merge patch-1;
- push origin;
- create PR

**Comment by ragekit** [comment]
hum, that makes sense. I'll try again when i'll have a mn

2015-02-26 11:24 GMT+01:00 Jack <notifications@github.com>:

**Pull request closed without merging**
