### PR TITLE
Adding auto-completion script for 'git checkout'

### PR DESCRIPTION
**Pull request by sweiss3**
Adding auto-completion script for 'git checkout', which will display the existing branches as auto-completion options

### CODE REVIEW

**Comment by RDeluxe** [comment]
Agreed.

**Comment by narnaud** [comment]
For the record, the git.lua in https://github.com/vladimir-kotikov/clink-completions does not work (there is an error loading it), see https://github.com/vladimir-kotikov/clink-completions/issues/6
The one working for me is the one from here: https://github.com/wate/clink_completion
But I'm not entirely happy, as it's not completing filename after "git checkout" anymore.

**Comment by vladimir-kotikov** [comment]
@narnaud it should work with clink@0.4.3. Could you pls check it?

**Comment by narnaud** [comment]
@vladimir-kotikov Indeed, fixed with clink@0.4.3, nice work.

**Comment by RDeluxe** [comment]
I'm sorry, I don't have a good knowledge of clink. Those lua scripts are supposed to be place in the cmder\vendor\clink\profile (not created by default) folder or in the cmder\config ?

**Comment by narnaud** [comment]
@RDeluxe In cmder/config.
Make sure to use the latest clink

**Comment by RDeluxe** [comment]
I replaced the previous git.lua by the new one. I have a weird {git} at the end, and an error ...
http://i.imgur.com/A4u3iJs.png
I have latest clink.

**Comment by narnaud** [comment]
@RDeluxe You should not replace the old one:
* the git.lua in cmder is used to display the git branch in the prompt
* the git.lua from @vladimir-kotikov is used for git completion (command and branch)

Here is how to do:
1) Rename the existing git.lua (from cmder) into prompt.lua (for example)
2) Copy the git.lua from clink-completions into cmder/config
3) Delete all lines in this git.lua from 450 to the end (or you'll have some errors)
4) Done, enjoy

**Comment by RDeluxe** [comment]
Whoa, thanks, it works now. I tried to add both, but I did not know this line deletion thing ...
I think this little tutorial will come handy for others, until this script is integrated in cmder.

**Comment by vladimir-kotikov** [comment]
> until this script is integrated in cmder.

Will try to make it ASAP :)

**Comment by narnaud** [comment]
@vladimir-kotikov I wonder if there's a way to fix one issue I have with this script: there's no more completion on filename.

For example:
git checkout <tab>
shows all branches, that's what I expect.
But when I start typing, and there's no more completion on branch, I would expect to have completion on filename (to reset it).

Is it doable?

**Comment by vladimir-kotikov** [comment]
Hey @narnaud Your wish come true :) Check git.lua from https://github.com/vladimir-kotikov/clink-completions/tree/dev

The approach now is following: `git checkout {TAB}` will print both branches and pathspecs. Branches will be marked with asterisks.
I've also tried to mark branches with separate colour but it seems that something is broken in clink color handling (https://github.com/mridgers/clink/issues/279). Will digg deeper and try to find workaround

**Comment by narnaud** [comment]
@vladimir-kotikov Works like a charm, nice work!

**Comment by RDeluxe** [comment]
It's working for push and checkout, but not for pull. Don't know if it's doable !

Thanks for the amazing work, this was really needed in cmder :+1:

**Comment by vladimir-kotikov** [comment]
@RDeluxe Check https://github.com/vladimir-kotikov/clink-completions/commit/8c67ffb47b4617db1cc22c6710a4aeda079c9b80

**Comment by RDeluxe** [comment]
@vladimir-kotikov Tks ! That's working :dancers:

**Comment by rmorrin** [comment]
@vladimir-kotikov I've updated my clink to the 0.4.3 release and have the git completions working now - thanks! One thing I have noticed is that the CTRL + L shortcut seems to have stopped working properly, i.e. the screen isn't being cleared properly. Do you have this issue also? Any ideas on how to fix it?

**Comment by rmorrin** [comment]
@vladimir-kotikov Not to worry - managed to resolve the issue by updating to the latest ConEmu release! Git completions are all working for me now. :+1: 

I didn't remove anything from git.lua and haven't had any issues so far. Which errors where you referring to?

**Comment by RDeluxe** [comment]
Hi @vladimir-kotikov . I realized that some commands do not support auto-completion : 
- git push with a " :mybranch" will not autocomplete the branch name
- git rebase
- git merge does not seem to work

**Comment by vladimir-kotikov** [comment]
Hey @RDeluxe there is a bunch of git commands doesn't have a completions of course. I hadn't a motivation to implement all of them since i'm using only limited set of git functionality. If you're lacking some functionality, pls. file an issue at https://github.com/vladimir-kotikov/clink-completions/issues I believe, this thread is not the best place for feature requests :)

**Comment by RDeluxe** [comment]
True. Wille do that !

**Comment by killua99** [comment]
Tested on clink 0.4.4 and it work.

**Comment by MartiUK** [comment]
@vladimir-kotikov I'm planning on using your extended completions in the next version. Anything I should consider?

**Comment by vladimir-kotikov** [comment]
@MartiUK, nice to hear this!
Which way are you planning to do that? I would prefer to include them via reference to sources archive rather than just copying them to your repo, if it is possible.

Also i'm working on improving compatibility with cmder and integrating prompt replacements for git and hg. When this will be done you could just replace the embedded completions with the ones from my repo. I'm planning to finish this work till the start of next week.

**Comment by MartiUK** [comment]
@vladimir-kotikov Yes, I was planning on sticking it in the vendors.json and figuring out the best way to integrate them correctly.

**Comment by vladimir-kotikov** [comment]
Well, i see two options:
 - update build script so it could take one more parameter from `sources.json` - target path for specific component

- to have one lua script inside `config` directory that will load all other completion scripts from `vendor/completions` directory.

**Comment by vladimir-kotikov** [comment]
Looks like the second option is more flexible and intuitive. There is a sample for similar functionality here: https://github.com/bliker/cmder/pull/189/files#diff-814cfb7ac1b91bf911b5054dea006ed4R14

**Comment by vladimir-kotikov** [comment]
@MartiUK you can find PR for this here: https://github.com/bliker/cmder/pull/174

**Pull request closed without merging**
