### PR TITLE
Preview PR for including external completions into Cmder

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
It does the following:
- Moves all Cmder's prompt handling routines to cmder.lua. Purpose - exclude collisions with existing modules and reflect the fact that it is a Cmder own items.
- Adds external lua modules search'n'load logic
- Adds reference to completions repo to sources.json

### CODE REVIEW

**Comment by MartiUK** [comment]
Have you run a build using build.ps1, and does it extract the file fine?

**Comment by vladimir-kotikov** [comment]
Yep. Just tried again and it works.
Note that im planning to push some minor stuff to my repo and then release a 0.1.0 version so you probably would need to change a link to archive before release.

**Comment by MartiUK** [comment]
@vladimir-kotikov just commit your changes into your dev repo and let me know when it's ready to be pulled in.

**Comment by vladimir-kotikov** [comment]
@MartiUK. Looks lke i've done. I've updated a link to release archive, so all what you need it to merge this PR.

**Comment by MartiUK** [comment]
Thanks.

**Pull request merged**
