### PR TITLE
Extend init.bat

### PR DESCRIPTION
**Pull request by fredericseiler**
Extend the main init.bat with custom modifications (like prompt enhancements).

### CODE REVIEW

**Comment by fredericseiler** [comment]
The purpose of this PR is to override or add some defaults to the init script without modifying vendor\init.bat (for safe update).

ex. my overrided prompt in config\init.bat (with custom .lua) :

```
@prompt $+{path}{cgit}$_{arrow}
```

The result :

image

**Comment by sc0tt** [comment]
Oh man, this will be nice. +1

**Comment by Arcovion** [comment]
+1

**Comment by fredericseiler** [comment]
Whoops, I didn't see @narnaud's #367...

**Comment by fredericseiler** [comment]
Better implementation (IMO) : #367

**Comment by fredericseiler** [comment]
Better implementation (IMO) : #367

**Pull request closed without merging**
