### PR TITLE
Adding mercuial prompt

### PR DESCRIPTION
**Pull request by utek**
Similar to git prompt I've added mercurial prompt.

### CODE REVIEW

**Comment by MartiUK** [comment]
:+1: Looks good to me Thanks.

**Comment by vBm** [comment]
Thanks to this PR now we have {hg} visible all the time when using git repos.

I don't understand why did you change config/git.lua ?

**Comment by vBm** [comment]
Seems my comment is gone.
Here it goes again.


Thanks to this PR now we have {hg} visible all the time when using git repos. I don't understand why did you change config/git.lua ?


Quick fix for this would be to completely remove git.lua since it seems that everything was merged into cmder.lua

**Comment by Stanzilla** [comment]
Filed as https://github.com/bliker/cmder/issues/494

**Pull request merged**
